### ISSUE TITLE
Issue with spaces in the path to the data folder

### ISSUE THREAD

**Issue by adityagp** [zenvisage/zenvisage#101]
Throws an exception:

Exception in thread "main" java.io.FileNotFoundException: /Users/aditya/Box%20Sync/Research%20Implementation/VisualizationProj/implementation-zenvisage/zenvisage/target/classes/data/real_estate.txt (No such file or directory)
    at java.io.FileInputStream.open0(Native Method)
    at java.io.FileInputStream.open(FileInputStream.java:195)
    at java.io.FileInputStream.<init>(FileInputStream.java:138)
    at java.io.FileInputStream.<init>(FileInputStream.java:93)
    at java.io.FileReader.<init>(FileReader.java:58)
    at edu.uiuc.zenvisage.data.remotedb.SchemeToMetatable.schemeFileToMetaSQLStream(SchemeToMetatable.java:72)
    at edu.uiuc.zenvisage.service.ZvMain.uploadDatasettoDB(ZvMain.java:157)
    at edu.uiuc.zenvisage.server.ZvServer.loadDemoDatasets(ZvServer.java:108)
    at edu.uiuc.zenvisage.server.ZvServer.main(ZvServer.java:53)

**Comment by wookhuk** [comment]
So this problem can be resolved if you place the files in the target folder. Chaoran explained me to this earlier and might have a better idea on why this is happening.

**Comment by superchaoran** [comment]
Yes. I know the crux of this problem. Since tarique has implemented a auto loading functionality when the server starts, we need to have datasets and schemas inside data folder by default. You can see the error is coming from ZvServer.loadDemoDatasets(ZvServer.java:108). so by putting those datasets and schema in dropbox, this issue can be solved.(remember that we moved github datasets to a dropbox link?)
