### ISSUE TITLE
Better error message for data upload

### ISSUE THREAD

**Issue by dorisjlee** [zenvisage/zenvisage#191]
When user selects an improper type during data upload, the backend throws an error, this is not displayed on the frontend, instead a generic message is returned. 
```
org.postgresql.util.PSQLException: ERROR: invalid input syntax for integer: "5152.0"
  Where: COPY kepler, line 2, column teff: "5152.0"
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2182)
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1911)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:173)
```
For example on the kepler dataset, teff column is autodetected as int, whereas it is actually float. We should show on the frontend at least what coulmn needs to be fixed. Also look into whether there is a mistake in detecting the teff column as int not float?

**Comment by dorisjlee** [comment]
Issue assigned to Marc. @jaywoo123  might need to help explain the automatic type coercion code for the second part of this issue (i.e. why 5152 int is being parsed as 5152.0 float) .
