### ISSUE TITLE
File path cannot have spaces within them

### ISSUE THREAD

**Issue by adityagp** [zenvisage/zenvisage#199]
Leads to an exception due to incorrect interpretation of spaces in the file path, especially for built in txt files.

"Exception in thread "main" java.io.FileNotFoundException: /Users/adityagp/Box%20Sync/Research%20Implementation/VisualizationProj/Zenvisage-2018-v02/zenvisage/target/classes/data/real_estate.txt (No such file or directory)
at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(FileInputStream.java:220)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:158)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:113)
	at java.base/java.io.FileReader.<init>(FileReader.java:58)
	at edu.uiuc.zenvisage.data.remotedb.SchemeToMetatable.schemeFileToMetaSQLStream(SchemeToMetatable.java:82)
	at edu.uiuc.zenvisage.service.ZvMain.uploadDatasettoDB(ZvMain.java:183)
	at edu.uiuc.zenvisage.server.DatabaseAutoLoader.loadDemoDatasets(DatabaseAutoLoader.java:120)
	at edu.uiuc.zenvisage.server.DatabaseAutoLoader.run(DatabaseAutoLoader.java:129)
	at edu.uiuc.zenvisage.server.ZvServer.start(ZvServer.java:46)
	at edu.uiuc.zenvisage.server.ZvServer.main(ZvServer.java:58)

**Comment by dorisjlee** [comment]
Tested @Renxuanwang's bugfix that resolved the issue.
